import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaChevronDown, FaChevronUp } from 'react-icons/fa';

const faqData = [
  {
    question: "What is HealthCareInsight?",
    answer: "HealthCareInsight is an AI-powered app that monitors your health metrics, provides personalized insights, and offers expert health advice."
  },
  {
    question: "How does HealthCareInsight monitor health metrics?",
    answer: "HealthCareInsight uses advanced AI models to analyze data from your health tracking devices and provide comprehensive health reports."
  },
  {
    question: "What kind of insights does HealthCareInsight offer?",
    answer: "HealthCareInsight offers insights related to your fitness, nutrition, sleep, and overall well-being based on your health data."
  },
  {
    question: "How does expert advice work?",
    answer: "HealthCareInsight connects you with health experts who provide personalized advice based on your health data and goals."
  },
  {
    question: "Can HealthCareInsight answer health-related questions?",
    answer: "Yes, you can ask specific health-related questions, and HealthCareInsight will provide accurate and insightful answers generated by its advanced AI models."
  }
];

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <motion.div 
      className="mb-4 rounded-lg overflow-hidden shadow-lg bg-white"
      initial={false}
    >
      <motion.button
        className="flex justify-between items-center w-full text-left px-6 py-4 text-black font-semibold"
        onClick={() => setIsOpen(!isOpen)}
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
      >
        <span className="text-lg">{question}</span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          {isOpen ? <FaChevronUp /> : <FaChevronDown />}
        </motion.div>
      </motion.button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="px-6 py-4 bg-gray-50 text-gray-800"
          >
            {answer}
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const FAQ = () => {
  return (
    <div className="bg-gray-100 py-16">
      <div className="container mx-auto px-6">
        <h2 className="text-4xl font-bold text-center mb-12 text-yellow-500">Frequently Asked Questions</h2>
        <div className="max-w-3xl mx-auto">
          {faqData.map((item, index) => (
            <FAQItem key={index} question={item.question} answer={item.answer} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQ;
